"""
    Define pipelines here.
"""
#
#
# Don't forget to add your pipeline to the ITEM_PIPELINES setting
# See: https://docs.scrapy.org/en/latest/topics/item-pipeline.html


# useful for handling different item types with a single interface
import os.path
import sys
import json
import re
from toddler.items import HouseInfoItem
sys.path.append(os.path.dirname(os.path.dirname(__file__)))


class ToddlerPipeline:
    """
    Generated by scrapy framework .
    Define filters and  persistence logic here.
    """
    def __init__(self):
        """
        Define file properties.
        """
        self.file = None

    def open_spider(self, spider):
        """
        Do some operations when spider is opening;
        :param spider:
        :return:
        """
        self.file = open("./output/house_info.jsonl", "w", encoding="utf-8")

    def close_spider(self, spider):
        """
        Do some operations when spider is closing;
        :param spider:
        :return:
        """
        self.file.close()

    @staticmethod
    def __state_name_filter(full_address: str):
        """
        If state name  extracted from full address not in
        state_name_reject_list then return True,or return False;
        :param full_address: Full address string from HouseInfoItem.
        :return: Must Return True or False.
        """
        state_name_reject_list = ["NSW"]
        state_name = (
            re.compile("([A-Z]{2,}) [0-9]{4}$").search(full_address).groups(1)[0])
        if state_name not in state_name_reject_list:
            return True
        return None

    @staticmethod
    def __listing_type_filter(listing_type: str):
        """
        If listing_type in listing_type_access_list
        then return True,or return False;
        :param listing_type: Listing type string from HouseInfoItem.
        :return:Must Return True or False.
        """
        listing_type_access_list = ["FOR SALE", "FOR LEASE"]
        if listing_type.upper() in listing_type_access_list:
            return True
        return None

    def __house_info_filter(self, item):
        """
        AND operation on all filters;
        :param item: HouseInfoItem
        :return:Must return True of false.
        """
        return self.__listing_type_filter(
            item["listing_type"]
        ) and self.__state_name_filter(item["full_address"])

    def process_item(self, item, spider):
        """
        Calls by SpiderEngine;
        It filters and archives data;
        :param item:
        :param spider: Don's remove it
        or spiders will not work even though it didn't call explicitly.
        :return:
        """
        if isinstance(item, HouseInfoItem):
            if self.__house_info_filter(item):
                self.file.write(json.dumps(dict(item)) + "\n")
                return item
        return None
